<a href="https://colab.research.google.com/github/antoniorenno/POO_1/blob/main/Ol%C3%A1%2C_este_%C3%A9_o_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
F = float(input("Digite valor em Graus Farenheit: "))
C = (5/9)*(F-32)
print(f"O valor de {F}°F corresponde ao valor de {C}°C")

Digite valor em Graus Farenheit: 50
O valor de 50.0°F corresponde ao valor de 10.0°C


Digite valor em Graus Farenheit: 50
O valor de 50.0°F corresponde ao valor de 10.0°C